// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Code  int    `json:"code"`
	Msg   string `json:"msg"`
	Token string `json:"token"`
}

type Goodinfo struct {
	GoodsName  string `json:"goodsName,optional"`
	GoodsPrice string `json:"goodsPrice,optional"`
	GoodsNum   string `json:"goodsNum,optional"`
	GoodsRef   string `json:"goodsRef,optional"`
	GoodsId    string `json:"goodsId,optional"`
	GoodsImage string `json:"goodsImage,optional"`
}

type SearchRequest struct {
	Context string `json:"context"`
	Page    string `json:"page"`
	Limit   string `json:"limit"`
}

type SearchResponse struct {
	Goodinfo []Goodinfo `json:"goodinfo"`
}

type CreateGoodRequest struct {
	GoodsOneInfo Goodinfo `json:"goodsOneInfo"`
}

type CreateGoodResponse struct {
	GoodsOneInfo Goodinfo `json:"goodsOneInfo"`
}

type DelGoodRequest struct {
	Goodsid string `json:"goodsid"`
}

type DelGoodResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UpdateGoodRequest struct {
	GoodsOneInfo Goodinfo `json:"goodsOneInfo"`
}

type UpdateGoodResponse struct {
	GoodsOneInfo Goodinfo `json:"goodsOneInfo"`
}

type Orderinfo struct {
	Id         int     `json:"id,optional"`
	UserId     int     `json:"userId,optional"`
	GoodsId    int     `json:"goodsId,optional"`
	IsStatus   int8    `json:"isStatus,optional"`
	IsDel      int8    `json:"isDel,optional"`
	TotalPrice float64 `json:"totalPrice,optional"`
	DeleteAt   int     `json:"deleteAt,optional"`
	CreateAt   int     `json:"createAt,optional"`
	UpdateAt   int     `json:"updateAt,optional"`
	OrderNo    string  `json:"orderNo,optional"`
}

type Goods struct {
	GoodsId string `json:"goodsid"`
	Num     string `json:"num"`
}

type CreateOrder struct {
	Goods []Goods `json:"goods"`
}

type CreateOrderResp struct {
	PayUrl string `json:"payUrl"`
}

type NotifyRequest struct {
}

type NotifyResponse struct {
}

type DeleteOrder struct {
	Data Orderinfo `json:"data"`
}

type DeleteOrderResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UpdateOrder struct {
	Data Orderinfo `json:"data"`
}

type UpdateOrderResp struct {
	Data Orderinfo `json:"data"`
}

type SelectOrder struct {
	Page  string `json:"page"`
	Limit string `json:"limit"`
}

type SelectOrderResp struct {
	Data []Orderinfo `json:"data"`
}
