// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"2106A-zg6/orderAndGoods/goodsproject/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: GatewayHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notify",
				Handler: NotifysHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/search",
				Handler: SearchAllGoodsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/insertgood",
				Handler: InsertGoodsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/delGood",
				Handler: DelGoodsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/Updategood",
				Handler: UpdateGoodsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/createorder",
				Handler: CreateOrHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/DeleteOrder",
				Handler: DeleteOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/UpdateOrder",
				Handler: UpdateOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/SelectOrder",
				Handler: SelectOrderHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
